# -*- coding: utf-8 -*-
"""UPRAK 2 ALGO

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1glATPPAuFFPh9_LkW4bQ2sZBXZRrkc2G
"""

print('@@@@      @     @@@@ @     @')
print('@  @     @ @    @    @     ')
print('@ @     @   @   @@@@ @     @  ')
print('@  @   @ @@@ @  @    @     @   ')
print('@   @ @       @ @    @@@@@ @      ')
5
# Menerima tiga angka dari pengguna
angka1 = float(input("Masukkan angka pertama: "))
angka2 = float(input("Masukkan angka kedua: "))
angka3 = float(input("Masukkan angka ketiga: "))

# Mencari angka terbesar menggunakan kondisi if-else
if angka1 >= angka2 and angka1 >= angka3:
    angka_terbesar = angka1
elif angka2 >= angka1 and angka2 >= angka3:
    angka_terbesar = angka2
else:
    angka_terbesar = angka3

# Menampilkan hasil
print(f"Angka terbesar adalah: {angka_terbesar}")

print('@@@@      @     @@@@ @     @')
print('@  @     @ @    @    @     ')
print('@ @     @   @   @@@@ @     @  ')
print('@  @   @ @@@ @  @    @     @   ')
print('@   @ @       @ @    @@@@@ @      ')

import math

def hitung_sisi_a(sisi_b, sisi_c):
    return math.sqrt(sisi_c*2 - sisi_b*2)

def hitung_sisi_b(sisi_a, sisi_c):
    return math.sqrt(sisi_c*2 - sisi_a*2)

def hitung_sisi_c(sisi_a, sisi_b):
    return math.sqrt(sisi_a*2 + sisi_b*2)

print("Kalkulator Pythagoras")
print("Pilih operasi:")
print("1. Hitung sisi a")
print("2. Hitung sisi b")
print("3. Hitung sisi c")
pilihan = int(input("Masukkan nomor operasi yang diinginkan (1/2/3): "))

if pilihan == 1:
    sisi_b = float(input("Masukkan panjang sisi b: "))
    sisi_c = float(input("Masukkan panjang sisi c: "))
    while sisi_c < sisi_b:
        print("Nilai c tidak boleh lebih kecil dari nilai b.")
        sisi_c = float(input("Masukkan ulang panjang sisi c: "))
    sisi_a = hitung_sisi_a(sisi_b, sisi_c)
    print(f"Panjang sisi a adalah: {sisi_a}")
elif pilihan == 2:
    sisi_a = float(input("Masukkan panjang sisi a: "))
    sisi_c = float(input("Masukkan panjang sisi c: "))
    while sisi_c < sisi_a:
        print("Nilai c tidak boleh lebih kecil dari nilai a.")
        sisi_c = float(input("Masukkan ulang panjang sisi c: "))
    sisi_b = hitung_sisi_b(sisi_a, sisi_c)
    print(f"Panjang sisi b adalah: {sisi_b}")
elif pilihan == 3:
    sisi_a = float(input("Masukkan panjang sisi a: "))
    sisi_b = float(input("Masukkan panjang sisi b: "))
    sisi_c = hitung_sisi_c(sisi_a, sisi_b)
    print(f"Panjang sisi c adalah: {sisi_c}")
else:
    print("Pilihan operasi tidak valid. Harap masukkan 1, 2, atau 3.")